---
apiVersion: v1
kind: Namespace
metadata:
  name: okay

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okay
  namespace: okay
spec:
  selector:
    matchLabels:
      app: okay
  replicas: 2
  template:
    metadata:
      labels:
        app: okay
    spec:
      containers:
      - name: okay
        image: hashicorp/http-echo
        args:
          - "-text=okay"
        ports:
          - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: okay
  namespace: okay
spec:
  ports:
    - port: 80
      targetPort: 5678
  selector:
    app: okay
    
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: okay
  namespace: okay
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
    - hosts:
        - "okay.colecarter.dev"
      secretName: tls-okaydotcolecarterdotdev
  rules:
    - host: okay.colecarter.dev
      http:
        paths:
          - backend:
              serviceName: okay
              servicePort: 80
